packages:
  - "playground"

allowBuilds:
  '@parcel/watcher': false
  esbuild: false
  unrs-resolver: false

overrides:
  "@nuxt/schema": "4.6.0"
  "@nuxtjs/partytown": "workspace:*"

shamefullyHoist: true

strictPeerDependencies: false
