packages:
  - "playground"

allowBuilds:
  '@parcel/watcher': false
  esbuild: false
  unrs-resolver: false

overrides:
  "@nuxt/schema": "4.4.6"
  "@nuxtjs/partytown": "link:./"

shamefullyHoist: true

strictPeerDependencies: false
